@@ -275,86 +275,3 @@ def stream_slices(
         for _slice in accounts.stream_slices():
             for account in accounts.read_records(SyncMode.full_refresh, _slice):
                 yield {""account_id"": account[""Id""], ""customer_id"": account[""ParentCustomerId""]}
-
-
-class AdGroups(BingAdsCampaignManagementStream):
-    """"""
-    Gets the ad groups for all provided accounts.
-    API doc: https://docs.microsoft.com/en-us/advertising/campaign-management-service/getadgroupsbycampaignid?view=bingads-13
-    AdGroup schema: https://docs.microsoft.com/en-us/advertising/campaign-management-service/adgroup?view=bingads-13
-    Stream caches incoming responses to be able to reuse this data in Ads stream
-    """"""
-
-    primary_key = ""Id""
-    # Stream caches incoming responses to avoid duplicated http requests
-    use_cache: bool = True
-    data_field: str = ""AdGroup""
-    operation_name: str = ""GetAdGroupsByCampaignId""
-    additional_fields: str = ""AdGroupType AdScheduleUseSearcherTimeZone CpmBid CpvBid MultimediaAdsBidAdjustment""
-
-    parent_key_to_foreign_key_map = {""CampaignId"": ""campaign_id"", ""AccountId"": ""account_id"", ""CustomerId"": ""customer_id""}
-
-    def request_params(
-        self,
-        stream_slice: Mapping[str, Any] = None,
-        **kwargs: Mapping[str, Any],
-    ) -> MutableMapping[str, Any]:
-        return {""CampaignId"": stream_slice[""campaign_id""], ""ReturnAdditionalFields"": self.additional_fields}
-
-    def stream_slices(
-        self,
-        **kwargs: Mapping[str, Any],
-    ) -> Iterable[Optional[Mapping[str, Any]]]:
-        campaigns = Campaigns(self.client, self.config)
-        accounts = Accounts(self.client, self.config)
-        for _slice in accounts.stream_slices():
-            for account in accounts.read_records(SyncMode.full_refresh, _slice):
-                for campaign in campaigns.read_records(
-                    sync_mode=SyncMode.full_refresh, stream_slice={""account_id"": account[""Id""], ""customer_id"": account[""ParentCustomerId""]}
-                ):
-                    yield {""campaign_id"": campaign[""Id""], ""account_id"": account[""Id""], ""customer_id"": account[""ParentCustomerId""]}
-
-
-class Ads(BingAdsCampaignManagementStream):
-    """"""
-    Retrieves the ads for all provided accounts.
-    API doc: https://docs.microsoft.com/en-us/advertising/campaign-management-service/getadsbyadgroupid?view=bingads-13
-    Ad schema: https://docs.microsoft.com/en-us/advertising/campaign-management-service/ad?view=bingads-13
-    """"""
-
-    primary_key = ""Id""
-    data_field: str = ""Ad""
-    operation_name: str = ""GetAdsByAdGroupId""
-    additional_fields: str = ""ImpressionTrackingUrls Videos LongHeadlines""
-    ad_types: Iterable[str] = [
-        ""Text"",
-        ""Image"",
-        ""Product"",
-        ""AppInstall"",
-        ""ExpandedText"",
-        ""DynamicSearch"",
-        ""ResponsiveAd"",
-        ""ResponsiveSearch"",
-    ]
-
-    parent_key_to_foreign_key_map = {""AdGroupId"": ""ad_group_id"", ""AccountId"": ""account_id"", ""CustomerId"": ""customer_id""}
-
-    def request_params(
-        self,
-        stream_slice: Mapping[str, Any] = None,
-        **kwargs: Mapping[str, Any],
-    ) -> MutableMapping[str, Any]:
-        return {
-            ""AdGroupId"": stream_slice[""ad_group_id""],
-            ""AdTypes"": {""AdType"": self.ad_types},
-            ""ReturnAdditionalFields"": self.additional_fields,
-        }
-
-    def stream_slices(
-        self,
-        **kwargs: Mapping[str, Any],
-    ) -> Iterable[Optional[Mapping[str, Any]]]:
-        ad_groups = AdGroups(self.client, self.config)
-        for slice in ad_groups.stream_slices(sync_mode=SyncMode.full_refresh):
-            for ad_group in ad_groups.read_records(sync_mode=SyncMode.full_refresh, stream_slice=slice):
-                yield {""ad_group_id"": ad_group[""Id""], ""account_id"": slice[""account_id""], ""customer_id"": slice[""customer_id""]}