@@ -1,15 +1,15 @@
 SCRIPT_TYPE_FIX = 101
-SCRIPT_TYPE_PORMPT = 102
+SCRIPT_TYPE_PROMPT = 102
 SCRIPT_TYPE_SYSTEM = 103
 SCRIPT_TYPES = {
     ""固定剧本"": SCRIPT_TYPE_FIX,
-    ""Prompt"": SCRIPT_TYPE_PORMPT,
+    ""Prompt"": SCRIPT_TYPE_PROMPT,
     ""系统角色"": SCRIPT_TYPE_SYSTEM,
 }
 
 SCRIPT_TYPE_VALUES = {
     SCRIPT_TYPE_FIX: ""固定剧本"",
-    SCRIPT_TYPE_PORMPT: ""Prompt"",
+    SCRIPT_TYPE_PROMPT: ""Prompt"",
     SCRIPT_TYPE_SYSTEM: ""系统角色"",
 }
 