@@ -1,3 +1,5 @@
+""""""Example of reannotating the WildChat dataset using curator.""""""
+
 import logging
 
 from datasets import load_dataset
@@ -13,10 +15,27 @@
 
 
 def prompt_func(row):
+    """"""Extract the first message from a conversation to use as the prompt.
+
+    Args:
+        row: Dictionary containing a conversation from the WildChat dataset
+
+    Returns:
+        The first message content to be used as the prompt
+    """"""
     return row[""conversation""][0][""content""]
 
 
 def parse_func(row, response):
+    """"""Parse the model response into the desired output format.
+
+    Args:
+        row: Dictionary containing the original conversation
+        response: The new response generated by the model
+
+    Returns:
+        Dictionary containing the original instruction and new response
+    """"""
     instruction = row[""conversation""][0][""content""]
     return {""instruction"": instruction, ""new_response"": response}
 